language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: UojaIKZc1DeAOOcl3oO/ECw5O5Ru91tdhPqGOT9hSIKbiWz85JtFQ3WHB6MGIVRmcUJp1UOA/u9QazezzSnSkoDrDrZdIKiI8/0t4szA1p+05Hz8Aj5XWvtPUCKqeD0TsfmUZiD1zLiZ1UOfk6UUN8k96P8zUO7mzWCRUvRPZ7YT54ZJMM4tnbH+roB404yXJfT+qpng/qsp+LnSOjLJqghjo4ClzYv9c03eW9lMH6WgKiFcBuWCKXs/QyACatFfSmDYkBgn0KBjZVQO4Um9yEAaswZ4MCc1QceWbScHlqXXw78wIAfzwlBCXgCkpGd9jzbEy5KBywefrJs7ogNeMY99L0MG/QiCfF/TEQGrDGog36scJOK4bg55Fc8d4i/4P8Wpel/7BukbVTL4ONZnV9E4MKSPonj6uEapXR5ua4/AzjWAMcZIBNyhcvJbLAKWiMObqWgzlRu7KNhC8/hNqTSxiQ3dvxgNEq9ybE3tro19yTuFTUpFEjELkeOL1ORi8Rw6JrrNprMLcENlwkDLm9MaCnu4w12DJV/BDvbR+k8W1Q4wngwkMDVNX3rusjIvpzlHz2VLQiVXxC7MZHUP6qgQvWtYtqTGaIQcIyaWJphdkd2TX/d5RD7NOAL2pJfhDnbaWpnqW1Y1tqiI/qNuPUUhGfmjDodKNGRM+h76re0=
  # REGISTRY_TOKEN slug=sncf editor=cozy space=default
  - secure: E7DVcVX2H56jXk4gfYTnh/sCIeavZrwMjvLZXRl4AFzgSTUZmFXe1xAKHo0QPYtIuVpgAvJTNFgXob7mWf4EofLo0QrNz3vPk3jn5IG0OGuF4t5TB9BtlLgT/oS20Z89nLR/OBfEPihcmobw9BAahSd8wFuI1d/29dyTwNhA5m0axYNWUuxn1fTS2p35nO+eh2QPDD7kmlES8OwZW32U8hMRJ1rHmzT5/Ph28Y1XR14XB6fjK9jty3m822RcglfzgPGDCDpx7fMh1PgBV9G7kcyjPloAwSmmY9QVujaRFdw0cAXKXCFKsNq1TVav6SghrW20hKJbGKKCM1/NzmzaW6OXspLO7szHfdgsDIZa31tCS8KRpakWNFEyV4wbxE5y54FKxMcAojh8uLDeMLD1dW1oZAhcp345Bgj7EeVklN9y1fX4LFQib/JTKhK1cG0NRGDMQ9BiwERYkxx9S+3xhP9IugF0l908cG3klSJuKL6rLyugQxdvxANEEO4QC2+63XpYVRf1qMSLbhbFWQf2QffXoEIZHX8Yzc96Uscv8zDXyH4i9CI5wIgDVpIId7CINOSxq3GqLM+1SpRYY8PgtrhzCWSOpWBnAESxGT15ZbOfRBqEEGU7uu8e6b6Kxcjx9eqq7Xj1Dp7Ixcqj+MUAzpoA+eD5MoR6eK+fuuanXDY=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
